# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dataG2F',
                'doc_host': 'https://DanielKick-USDA.github.io',
                'git_url': 'https://github.com/DanielKick-USDA/dataG2F',
                'lib_path': 'dataG2F'},
  'syms': {'dataG2F.core': {'dataG2F.core.foo': ('core.html#foo', 'dataG2F/core.py')}}}
